version: '3.8'

services:
  storage:
    container_name: map_storage
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: map
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 777
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d map -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    container_name: app
    build:
      context: .
      dockerfile: /web/src/main/docker/Dockerfile.jvm
    image: quarkus/application
    depends_on:
      storage:
        condition: service_healthy
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      quarkus.datasource.username: postgres
      quarkus.datasource.password: postgres
      quarkus.datasource.jdbc.url: jdbc:postgresql://storage:5432/map